import { RPECandidateRef } from '../rpe-candidate/index.js';
import { 
  RPECandidateGeneratorCandidateDescription,
} from '../rpe-candidate-generator/index.js';

/**
 * A candidate generated by the RPE candidate generator.
 * @category Reflective Prompt Evolution
 */
export interface CandidateGeneratorOutputCandidate
  extends RPECandidateGeneratorCandidateDescription
{
  /**
   * Reference to the candidate.
   */
  candidateRef: RPECandidateRef;
}

/**
 * Output for the RPE candidate generator.
 * @category Reflective Prompt Evolution
 */
export interface CandidateGeneratorOutput {
  /**
   * New candidates.
   */
  candidates: CandidateGeneratorOutputCandidate[];
}