import { LLMUsage } from '../../llm/index.js';
import { RPECandidate, RPECandidateRef } from '../rpe-candidate/index.js';
import { 
  RPECandidateGeneratorChange,
} from '../rpe-candidate-generator/index.js';

/**
 * Candidate generated by the RPE candidate generator.
 * @category Reflective Prompt Evolution
 */
export interface CandidateGeneratorOutputCandidate {
  /**
   * New candidate.
   */
  candidate: RPECandidate;

  /**
   * Changes made to the candidate.
   */
  changes: RPECandidateGeneratorChange[];

  /**
   * Usage of the model.
   */
  usage?: LLMUsage;
}

/**
 * Output for the RPE candidate generator.
 * @category Reflective Prompt Evolution
 */
export interface CandidateGeneratorOutput {
  /**
   * New candidates.
   */
  candidates: CandidateGeneratorOutputCandidate[];
}

/**
 * Candidate for the RPE candidate generator stored in the state.
 * @category Reflective Prompt Evolution
 */
export interface CandidateGeneratorCandidate {
  /**
   * Reference to the generated candidate.
   */
  candidateRef: RPECandidateRef;

  /**
   * Changes made to the candidate.
   */
  changes: RPECandidateGeneratorChange[];

  /**
   * Usage of the model.
   */
  usage?: LLMUsage;
} 