import { RPECandidate } from '../rpe-candidate/index.js';
import { RPEState } from '../rpe-state/index.js';
import { 
  RPEExecutor,
  RPEExecutorOutput,
} from '../rpe-executor/index.js';

/**
 * Generates responses for the given candidates using the given executor.
 * @param state - State of the RPE process.
 * @param candidates - Candidates to generate responses for.
 * @param executor - Executor to use for the response generation.
 * @returns Output generated by the executor.
 */
export async function generateResponses(
  state: RPEState,
  candidates: RPECandidate[],
  executor: RPEExecutor,
): Promise<RPEExecutorOutput> {
  const output = await executor.run(state, { candidates });
  return output;
}