import { RPEProperties } from '../rpe-info/index.js';
import { RPECandidate } from '../rpe-candidate/index.js';
import { RPEAggregatorOutput } from '../rpe-aggregator/index.js';
import { RPEAnalyzerOutput } from '../rpe-analyzer/index.js';
import { LLMUsage } from '../../llm/index.js';

/**
 * Input for the RPE candidate generator.
 * @category Reflective Prompt Evolution
 */
export interface RPECandidateGeneratorInput {
  /**
   * Original candidate.
   */
  candidate: RPECandidate;

  /**
   * Aggregation of the evaluations.
   */
  aggregation: RPEAggregatorOutput;

  /**
   * Analysis of the candidate.
   */
  analysis: RPEAnalyzerOutput;
}

/**
 * Change made to the candidate.
 * @category Reflective Prompt Evolution
 */
export interface RPECandidateGeneratorChange {
  /**
   * Description of the change.
   */
  description: string;

  /**
   * Reasoning for the change.
   */
  reasoning: string;
}

/**
 * A candidate generated by the RPE candidate generator.
 * @category Reflective Prompt Evolution
 */
export interface RPECandidateGeneratorCandidate {
  /**
   * New candidate.
   */
  candidate: Omit<RPECandidate, 'candidateId'>;

  /**
   * Changes made to the candidate.
   */
  changes: RPECandidateGeneratorChange[];

  /**
   * Usage of the model.
   */
  usage?: LLMUsage;
}

/**
 * Output for the RPE candidate generator.
 * @category Reflective Prompt Evolution
 */
export interface RPECandidateGeneratorOutput {
  /**
   * Generated candidates.
   */
  candidates: RPECandidateGeneratorCandidate[];
}

/**
 * Info of the RPE candidate generator.
 * @category Reflective Prompt Evolution
 */
export interface RPECandidateGeneratorInfo {
  /**
   * Name of the candidate generator.
   */
  name: string;

  /**
   * Properties of the candidate generator.
   */
  properties?: RPEProperties;
}

/**
 * Responsible for generating a new candidate based on the original candidate,
 * the aggregation of the evaluations and the analysis of the candidate.
 * @category Reflective Prompt Evolution
 */
export interface RPECandidateGenerator {
  /**
   * Generate a new candidate.
   * @param input - Input for the candidate generator.
   * @returns Candidate generator output.
   */
  run(input: RPECandidateGeneratorInput): Promise<RPECandidateGeneratorOutput>;

  /**
   * Get the info of the candidate generator.
   * @returns Info of the candidate generator.
   */
  getInfo(): Promise<RPECandidateGeneratorInfo>;
}