import { 
  ScalarMetric, 
  ScalarScoringScale,
} from '../../llm-as-a-judge/index.js';
import { ModelParameters } from '../../llm/index.js';
import { ModelProvider } from '../../model-provider/index.js';

/**
 * Input for the single-prompt LLM-as-a-judge RPE evaluator.
 * @category Reflective Prompt Evolution
 */
export interface SinglePromptJudgeRPEEvaluatorInput {
  /**
   * Model provider to use for the evaluator.
   * If not provided, the default model provider will be used.
   */
  modelProvider?: ModelProvider;

  /**
   * Model name to use for the executor.
   */
  modelName: string;

  /**
   * Model parameters to use for the executor.
   */
  modelParameters?: ModelParameters;

  /**
   * Scoring scale to use for the evaluation.
   * If not provided, the default scoring scale will be used.
   * @see {@link SCALAR_SCORING_DEFAULT}
   */
  scoringScale?: ScalarScoringScale;

  /**
   * Metrics to use for the evaluation.
   */
  metrics?: ScalarMetric[];

  /**
   * Prompt to use for the evaluation. The following placeholders are
   * injected:
   * - `prompt` - prompt used to generate the response,
   * - `response` - response generated by the model,
   * - `scoring_scale` - scoring scale,
   * - `expected_response` - expected response (canonical correct answer),
   * - `metrics` - metrics to return in the evaluation.
   * @default {@link SINGLE_PROMPT_JUDGE_RPE_EVALUATOR_PROMPT}
   */
  prompt?: string;
}