import { LLMUsage } from '../../llm/index.js';
import { RPEResponse } from '../rpe-core/index.js';
import { RPEProperties } from '../rpe-info/index.js';
import { RPEDatasetEntry } from '../rpe-dataset/index.js';
import { RPECandidate, RPECandidateRef } from '../rpe-candidate/index.js';

/**
 * Input for the RPE executor.
 * @category Reflective Prompt Evolution
 */
export interface RPEExecutorInput {
  /**
   * Candidate for which the response is generated.
   */
  candidates: RPECandidate[];
}

/**
 * Output for the RPE executor.
 * @category Reflective Prompt Evolution
 */
export interface RPEExecutorResponse {
  /**
   * Reference to the candidate for which the response is generated.
   */
  candidateRef: RPECandidateRef;

  /**
   * Dataset entry to use for the response generation.
   */
  datasetEntry: RPEDatasetEntry;

  /**
   * Response generated by the model.
   */
  response: RPEResponse;

  /**
   * Usage of the model.
   */
  usage?: LLMUsage;
}

/**
 * Output for the RPE executor.
 * @category Reflective Prompt Evolution
 */
export interface RPEExecutorOutput {
  /**
   * Responses generated by the executor.
   */
  responses: RPEExecutorResponse[];
}

/**
 * Info of the RPE executor.
 * @category Reflective Prompt Evolution
 */
export interface RPEExecutorInfo {
  /**
   * Name of the executor.
   */
  name: string;

  /**
   * Properties of the executor.
   */
  properties?: RPEProperties;
}

/**
 * An executor which takes a candidate and generates a response.
 * @category Reflective Prompt Evolution
 */
export interface RPEExecutor {
  /**
   * Execute a candidate.
   * @param input - Input for the executor.
   * @returns Executor output.
   */
  run(input: RPEExecutorInput): Promise<RPEExecutorOutput>;

  /**
   * Get the info of the executor.
   * @returns Info of the executor.
   */
  getInfo(): Promise<RPEExecutorInfo>;
}
