import { RPEProperties } from '../rpe-info/index.js';
import { RPEPrompt } from '../rpe-prompt/index.js';
import { RPEAggregatorOutput } from '../rpe-aggregator/index.js';
import { RPEAnalyzerOutput } from '../rpe-analyzer/index.js';
import { LLMUsage } from '../../llm/index.js';

/**
 * Input for the RPE prompt generator.
 * @category Reflective Prompt Evolution
 */
export interface RPEPromptGeneratorInput {
  /**
   * Original prompt.
   */
  prompt: RPEPrompt;

  /**
   * Aggregation of the evaluations.
   */
  aggregation: RPEAggregatorOutput;

  /**
   * Analysis of the prompt.
   */
  analysis: RPEAnalyzerOutput;
}

/**
 * Change made to the prompt.
 * @category Reflective Prompt Evolution
 */
export interface RPEPromptGeneratorChange {
  /**
   * Description of the change.
   */
  description: string;

  /**
   * Reasoning for the change.
   */
  reasoning: string;
}

/**
 * A prompt generated by the RPE prompt generator.
 * @category Reflective Prompt Evolution
 */
export interface RPEPromptGeneratorPrompt {
  /**
   * New prompt.
   */
  prompt: Omit<RPEPrompt, 'promptId'>;

  /**
   * Changes made to the prompt.
   */
  changes: RPEPromptGeneratorChange[];

  /**
   * Usage of the model.
   */
  usage?: LLMUsage;
}

/**
 * Output for the RPE prompt generator.
 * @category Reflective Prompt Evolution
 */
export interface RPEPromptGeneratorOutput {
  /**
   * Generated prompts.
   */
  prompts: RPEPromptGeneratorPrompt[];
}

/**
 * Info of the RPE prompt generator.
 * @category Reflective Prompt Evolution
 */
export interface RPEPromptGeneratorInfo {
  /**
   * Name of the prompt generator.
   */
  name: string;

  /**
   * Properties of the prompt generator.
   */
  properties?: RPEProperties;
}

/**
 * Responsible for generating a new prompt based on the original prompt,
 * the aggregation of the evaluations and the analysis of the prompt.
 * @category Reflective Prompt Evolution
 */
export interface RPEPromptGenerator {
  /**
   * Generate a new prompt.
   * @param input - Input for the prompt generator.
   * @returns Prompt generator output.
   */
  run(input: RPEPromptGeneratorInput): Promise<RPEPromptGeneratorOutput>;

  /**
   * Get the info of the prompt generator.
   * @returns Info of the prompt generator.
   */
  getInfo(): Promise<RPEPromptGeneratorInfo>;
}