import { RPEExecutorOutput } from './rpe-executor/index.js';

/**
 * Output for the RPE executor.
 * @category Reflective Prompt Evolution
 */
export interface ExecutorOutput {
  /**
   * Outputs (responses)generated by the RPE executor.
   */
  outputs: RPEExecutorOutput[];
}