import { runParallelBatchesOrThrow } from '../concurrency/index.js';
import { RPEDataset } from './rpe-dataset/index.js';
import { RPECandidate } from './rpe-candidate/index.js';
import { 
  RPEExecutor,
  RPEExecutorOutput,
} from './rpe-executor/index.js';
import { DEFAULT_EXECUTOR_PARALLELISM } from './executor-consts.js';
import { ExecutorOutput } from './executor-types.js';

/**
 * Generates responses for the given candidates and dataset
 * using the given executor.
 * @param candidates - Candidates to generate responses for.
 * @param dataset - Dataset to generate responses for.
 * @param executor - Executor to use for the response generation.
 * @returns Output containing the responses generated by the executor.
 */
export async function generateResponses(
  candidates: RPECandidate[],
  dataset: RPEDataset,
  executor: RPEExecutor,
  parallelism?: number,
): Promise<ExecutorOutput> {
  parallelism = parallelism ?? DEFAULT_EXECUTOR_PARALLELISM;

  // tasks
  const tasks: Promise<RPEExecutorOutput>[] = [];
  for (const candidate of candidates) {
    for (const datasetEntry of dataset.entries) {
      tasks.push(executor.run({ candidate, datasetEntry }));
    }
  }

  // run tasks in parallel
  const outputs = await runParallelBatchesOrThrow(tasks, parallelism);
  return { outputs };
}