import { RPEDataset } from './rpe-dataset/index.js';
import { RPEPrompt } from './rpe-prompt/index.js';
import { 
  RPEExecutor,
  RPEExecutorInput,
  RPEExecutorOutput,
} from './rpe-executor/index.js';
import { ExecutorOutput } from './executor-types.js';

/**
 * Generates responses for the given prompts and dataset using the given executor.
 * @param prompts - Prompts to generate responses for.
 * @param dataset - Dataset to generate responses for.
 * @param executor - Executor to use for the response generation.
 * @returns Output containing the responses generated by the executor.
 */
export async function generateResponses(
  prompts: RPEPrompt[],
  dataset: RPEDataset,
  executor: RPEExecutor,
): Promise<ExecutorOutput> {
  const outputs: RPEExecutorOutput[] = [];

  // TODO: parallelize this
  // for each prompt
  for (const prompt of prompts) {

    // for each dataset entry
    for (const datasetEntry of dataset.entries) {
      
      // generate response for the prompt and dataset entry
      const executorInput: RPEExecutorInput = {
        prompt,
        datasetEntry,
      };
      const output = await executor(executorInput);

      // keep the response
      outputs.push(output);
    }
  }

  return { outputs };
}