import { RPEExecutorOutput } from './rpe-executor/index.js';

/**
 * Output for the executor.
 */
export interface ExecutorOutput {
  /**
   * Outputs generated by the executor.
   */
  outputs: RPEExecutorOutput[];
}