import { LLMUsage } from '../llm/index.js';
import { RPEPrompt, RPEPromptRef } from './rpe-prompt/index.js';
import { 
  RPEPromptGeneratorChange,
} from './rpe-prompt-generator/index.js';

/**
 * Candidate prompt generated by the RPE prompt generator.
 * @category Reflective Prompt Evolution
 */
export interface PromptGeneratorOutputCandidate {
  /**
   * New prompt.
   */
  prompt: RPEPrompt;

  /**
   * Changes made to the prompt.
   */
  changes: RPEPromptGeneratorChange[];

  /**
   * Usage of the model.
   */
  usage?: LLMUsage;
}

/**
 * Output for the RPE prompt generator.
 * @category Reflective Prompt Evolution
 */
export interface PromptGeneratorOutput {
  /**
   * New prompt candidates.
   */
  candidates: PromptGeneratorOutputCandidate[];
}

/**
 * Candidate prompt for the RPE prompt generator stored in the state.
 * @category Reflective Prompt Evolution
 */
export interface PromptGeneratorCandidate {
  /**
   * Reference to the new (candidate) prompt.
   */
  promptRef: RPEPromptRef;

  /**
   * Changes made to the prompt.
   */
  changes: RPEPromptGeneratorChange[];

  /**
   * Usage of the model.
   */
  usage?: LLMUsage;
} 