import { RPEPrompt } from './rpe-prompt/index.js';
import { RPEDataset } from './rpe-dataset/index.js';
import { RPEExecutor } from './rpe-executor/index.js';
import { RPEEvaluator } from './rpe-evaluator/index.js';

/**
 * State of the RPE process.
 * @category Reflective Prompt Evolution
 */
export interface RPEState {
  /**
   * The prompts considered in the current iteration.
   */
  prompts: RPEPrompt[];

  /**
   * The current iteration of the RPE process (starting from 0).
   */
  iteration: number;
}

/**
 * Function to determine if the RPE should stop.
 * @category Reflective Prompt Evolution
 */
export type RPEStopFunc = (state: RPEState) => Promise<boolean>;

/**
 * Reflective Prompt Evolution (RPE) settings and configuration.
 * @category Reflective Prompt Evolution
 */
export interface RPEInput {
  /**
   * The initial prompts (seed prompts).
   */
  seed: RPEPrompt[];

  /**
   * The training dataset is used to evaluate the quality of the prompts
   * which are analyzed for failures.
   */
  trainingDataset: RPEDataset;

  /**
   * The validation dataset is used to evaluate the quality of the prompts
   * generated by the RPE.
   */
  validationDataset: RPEDataset;

  /**
   * Executor to use for the RPE. An executor is responsible for generating
   * responses to the prompts and dataset entries.
   * @see {@link llmRPEExecutor}
   */
  executor: RPEExecutor;

  /**
   * Evaluator to use for the RPE. An evaluator is responsible for evaluating
   * the responses.
   */
  evaluator: RPEEvaluator;

  /**
   * Function to determine if the optimization should stop.
   */
  stopFunc: RPEStopFunc;
}