import { RPEPrompt } from './rpe-prompt/index.js';
import { RPEDataset } from './rpe-dataset/index.js';
import { RPEExecutor } from './rpe-executor/index.js';
import { RPEEvaluator } from './rpe-evaluator/index.js';
import { RPEAggregator } from './rpe-aggregator/index.js';
import { RPEAnalyzer } from './rpe-analyzer/index.js';
import { RPEPromptGenerator } from './rpe-prompt-generator/index.js';
import { RPEPromptSelector } from './rpe-prompt-selector/index.js';
import { RPEStopFunc } from './rpe-stop/index.js';
import { RPEState } from './rpe-state/index.js';
import { RPEInsights } from './rpe-insights/index.js';

/**
 * Reflective Prompt Evolution (RPE) settings and configuration.
 * @category Reflective Prompt Evolution
 */
export interface RPEInput {
  /**
   * The initial prompts (seed prompts).
   */
  seed: RPEPrompt[];

  /**
   * The training dataset is used to evaluate the quality of the prompts
   * which are analyzed for failures.
   */
  trainingDataset: RPEDataset;

  /**
   * The validation dataset is used to evaluate the quality of the prompts
   * generated by the RPE.
   */
  validationDataset: RPEDataset;

  /**
   * Executor to use for the RPE. An executor is responsible for generating
   * responses to the prompts and dataset entries.
   * @see {@link llmRPEExecutor}
   */
  executor: RPEExecutor;

  /**
   * Number of concurrent executors to use. Defaults to 1 that means
   * that the executors are run sequentially.
   */
  executorParallelism?: number;

  /**
   * Evaluator to use for the RPE. An evaluator is responsible for evaluating
   * the responses.
   */
  evaluator: RPEEvaluator;

  /**
   * Number of concurrent evaluators to use. Defaults to 1 that means
   * that the evaluators are run sequentially.
   */
  evaluatorParallelism?: number;

  /**
   * Function to determine if the optimization should stop after evaluating
   * a set of responses.
   * @see {@link RPEState}
   */
  stopAfterEvaluation?: RPEStopFunc;

  /**
   * Number of concurrent aggregators to use. Defaults to 1 that means
   * that the aggregators are run sequentially.
   */
  aggregatorParallelism?: number;

  /**
   * Aggregator to use for the RPE. An aggregator is responsible for aggregating
   * the evaluations of a single prompt into a single evaluation.
   */
  aggregator: RPEAggregator;

  /**
   * Number of concurrent analyzers to use. Defaults to 1 that means
   * that the analyzers are run sequentially.
   */
  analyzerParallelism?: number;

  /**
   * Analyzer to use for the RPE. An analyzer is responsible for analyzing
   * the aggregated evaluations of a single prompt into a single analysis.
   */
  analyzer: RPEAnalyzer;

  /**
   * Number of concurrent prompt generators to use. Defaults to 1 that means
   * that the prompt generators are run sequentially.
   */
  promptGeneratorParallelism?: number;

  /**
   * Prompt generator to use for the RPE. A prompt generator is responsible for
   * generating a new prompt based on the aggregated evaluations and analyses.
   */
  promptGenerator: RPEPromptGenerator;

  /**
   * Prompt selector to use for the RPE. A prompt selector is responsible for
   * selecting the best prompts from the candidates.
   */
  promptSelector: RPEPromptSelector;

  /**
   * Function to determine if the optimization should stop after an iteration.
   */
  stopAfterIteration: RPEStopFunc;
}

/**
 * Output of an RPE process.
 * @category Reflective Prompt Evolution
 */
export interface RPEOutput {
  /**
   * The final prompts.
   */
  prompts: RPEPrompt[];

  /**
   * Insights from the RPE process.
   */
  insights: RPEInsights;
}