import { LLMUsage } from '../../llm/index.js';
import { RPEDatasetEntry } from '../rpe-dataset/index.js';
import { RPEPrompt } from '../rpe-prompt/index.js';

/**
 * Input for the RPE executor.
 * @category Reflective Prompt Evolution
 */
export interface RPEExecutorInput {
  /**
   * Prompt for which the response is generated.
   */
  prompt: RPEPrompt;

  /**
   * Dataset entry to use for the response generation.
   */
  datasetEntry: RPEDatasetEntry;
}

/**
 * Output for the RPE executor.
 * @category Reflective Prompt Evolution
 */
export interface RPEExecutorOutput {
  /**
   * Input for which the response is generated.
   */
  input: RPEExecutorInput;

  /**
   * Response generated by the model.
   */
  response: string;

  /**
   * Usage of the model.
   */
  usage?: LLMUsage;
}

/**
 * An executor which takes a prompt and generates a response.
 * @category Reflective Prompt Evolution
 */
export type RPEExecutor = (
  input: RPEExecutorInput,
) => Promise<RPEExecutorOutput>;