import { LLMUsage } from '../../llm/index.js';
import { RPEProperties } from '../rpe-info/index.js';
import { RPEDatasetEntry } from '../rpe-dataset/index.js';
import { RPEPrompt, RPEPromptRef } from '../rpe-prompt/index.js';

/**
 * Input for the RPE executor.
 * @category Reflective Prompt Evolution
 */
export interface RPEExecutorInput {
  /**
   * Prompt for which the response is generated.
   */
  prompt: RPEPrompt;

  /**
   * Dataset entry to use for the response generation.
   */
  datasetEntry: RPEDatasetEntry;
}

/**
 * Output for the RPE executor.
 * @category Reflective Prompt Evolution
 */
export interface RPEExecutorOutput {
  /**
   * Reference to the prompt for which the response is generated.
   */
  promptRef: RPEPromptRef;

  /**
   * Dataset entry to use for the response generation.
   */
  datasetEntry: RPEDatasetEntry;

  /**
   * Response generated by the model.
   */
  response: string;

  /**
   * Usage of the model.
   */
  usage?: LLMUsage;
}

/**
 * Info of the RPE executor.
 * @category Reflective Prompt Evolution
 */
export interface RPEExecutorInfo {
  /**
   * Name of the executor.
   */
  name: string;

  /**
   * Properties of the executor.
   */
  properties?: RPEProperties;
}

/**
 * An executor which takes a prompt and generates a response.
 * @category Reflective Prompt Evolution
 */
export interface RPEExecutor {
  /**
   * Execute a prompt.
   * @param input - Input for the executor.
   * @returns Executor output.
   */
  run(input: RPEExecutorInput): Promise<RPEExecutorOutput>;

  /**
   * Get the info of the executor.
   * @returns Info of the executor.
   */
  getInfo(): Promise<RPEExecutorInfo>;
}
